version: '2'
services:
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - '9090:9090'
    container_name: prometheus
    restart: always
    network_mode: host
    volumes:
      - '$HOME/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'

